---
# Install .NET SDK. An official deb package is available.

# .NET repo
- name: Add Microsoft prod APT repository (Debian)
  when: ansible_distribution == 'Debian'
  deb822_repository:
    name: packages-microsoft-com-prod
    types: deb
    uris: "https://packages.microsoft.com/{{ ansible_distribution|lower }}/{{ ansible_distribution_major_version }}/prod"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    suites: "{{ ansible_distribution_release|lower }}"
    components: main

- name: Add Microsoft prod APT repository (Ubuntu)
  when: ansible_distribution == 'Ubuntu'
  deb822_repository:
    name: packages-microsoft-com-prod
    types: deb
    uris: "https://packages.microsoft.com/{{ ansible_distribution|lower }}/{{ ansible_distribution_version }}/prod"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    suites: "{{ ansible_distribution_release|lower }}"
    components: main

- name: Ensure .NET SDK is up to date
  apt:
    update_cache: true
    package: dotnet-sdk-9.0
    state: present
