---
# Install .NET SDK. An official deb package is available.

# .NET repo
- name: Add an apt key .NET keyserver
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Fetch product list
  uri:
    url: "https://packages.microsoft.com/config/\
      {{ dotnet_distro }}/\
      {{ dotnet_release }}/\
      prod.list"
    return_content: yes
  register: this

- name: Register .NET SDK official repository
  apt_repository:
    filename: dotnet-sdk
    repo: "{{ this.content }}"

- name: Ensure .NET SDK is up to date
  apt:
    update_cache: yes
    package: dotnet-sdk-{{ dotnet_version }}
    state: present
