---
version: "2.1"
services:
  ssh:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_NAME: guest
        USER_GECOS: "Guest Account"
        USER_EMAIL: guest@morningrouti.ne
    container_name: ubuntu
    hostname: ubuntu
    environment:
      - PUBLIC_KEY_FILE=/ssh-key.pub
    volumes:
      - ./ssh-key.pub:/ssh-key.pub
    ports:
      - 2222:2222
    restart: unless-stopped
