---

# See also PR #76535 Ansible Pull + Ansible Galaxy Integration.
- hosts: localhost
  tasks:
    - name:  Install Ansible Galaxy requirements
      command: ansible-galaxy install -r roles/requirements.yml
