---

# See also PR #76535 Ansible Pull + Ansible Galaxy Integration.
- name: Install Ansible Galaxy requirements
  hosts: all
  tasks:
    - name: Install Ansible Galaxy requirements
      command: ansible-galaxy install -r roles/requirements.yml
      changed_when: true
