---
# Main playbook targeting localhost only.

- hosts: system

  roles:
    - utils
    - user
    # - adoptopenjdk
    # Segmentation fault on aarch64 Docker
    # - gradle
    - nodejs
    - corert
    - mvctrl

- hosts: user

  roles:
    - git
    - rustup
    - gradle_path
    - python3
    - npm
