---
# Main playbook targeting localhost only.

- name: Entrypoint for the root
  hosts: system

  roles:
    - utils
    - user
    - docker
    - terraform
    - golang
    - corert
    - aws_cli
    - arm_embedded
    - gcloud_cli

- name: Entrypoint for the user
  hosts: user

  roles:
    - git
    - rustup
    - jvm
    - gopath
    - arm_embedded_path
    - qemu_arm
    - python3
    - morgangraphics.ansible-role-nvm
