---
# Main playbook targeting localhost only.

- hosts: localhost

  roles:
    - utils
    - user
    - docker
    - adoptopenjdk
    - sbt
    - gradle
    - golang
    - nodejs
    - dotnet
    - corert
    - dynamodb_local

- hosts: user

  roles:
    - git
    - rustup
    - gradle_path
    - gopath
    - python3
    - npm
