---
# Main playbook targeting localhost only.

- hosts: localhost

  roles:
    - utils
    - user
    - docker
    - adoptopenjdk
    - sbt
    - terraform
    - gradle
    - golang
    - nodejs
    - dotnet
    - corert
    - dynamodb_local
    - aws_cli
    - mvctrl
    - arm_embedded
    - desktop

- hosts: user

  roles:
    - git
    - rustup
    # Disable wasmpack since installer fails to find rustup.
    # - wasmpack
    - gradle_path
    - gopath
    - arm_embedded_path
    - qemu_arm
    - python3
    - npm
    - yarn
    - flutter
