---
# Main playbook targeting localhost only.

- name: Entrypoint for the root
  hosts: system

  roles:
    - utils
    - user
    - corert
    - mvctrl

- name: Entrypoint for the user
  hosts: user

  roles:
    - git
    - rustup
    - python3
