---
# Main playbook targeting localhost only.

- name: Entrypoint for the root
  hosts: system

  roles:
    - utils
    - user
    - terraform
    - golang
    - nodejs
    - dotnet
    - corert
    - aws_cli

- name: Entrypoint for the user
  hosts: user

  roles:
    - git
    - rustup
    - jvm
    - gopath
    - python3
    - npm
