---
# Main playbook targeting localhost only.

- hosts: localhost

  roles:
    - ssh
    - user
    - adoptopenjdk
    - sbt
    - gradle
    - golang
    - nodejs

- hosts: user

  roles:
    - git
    - gopath
    - python3
