---
# Main playbook targeting localhost only.

- hosts: localhost

  roles:
    - user
    - docker
    - adoptopenjdk
    - sbt
    - gradle
    - golang
    - nodejs

- hosts: user

  roles:
    - git
    - rustup
    - gradle_path
    - gopath
    - python3
