---
# Main playbook targeting localhost only.

- hosts: system

  roles:
    - utils
    - user
    - adoptopenjdk
    # Segmentation fault on aarch64 Docker
    # - gradle
    - nodejs
    # No package matching 'dotnet-sdk-3.1' is available
    # - dotnet
    - corert
    - mvctrl

- hosts: user

  roles:
    - git
    - rustup
    - gradle_path
    - python3
    - npm
