---
# Defines a user.
#

- name: Check if a user already exists
  getent:
    database: passwd
    key: "{{ user_name }}"
    fail_key: false

# Later you need to set password, i.e., $ sudo passwd {{ user_name }}
- name: Create and set up the fresh user
  when: getent_passwd[user_name] == None
  block:

    - name: Create a fresh user with a disabled password
      user:
        name: '{{ user_name }}'
        comment: '{{ user_gecos }}'
        password: '!'
        shell: /bin/bash
        generate_ssh_key: true
        ssh_key_file: .ssh/id_ed25519
        ssh_key_type: ed25519
      register: new_user

    - name: Get the user's home
      set_fact:
        user_home: "{{ new_user.home }}"

    - name: Provide an authorized key
      authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ lookup('file', '{{ user_home }}/.ssh/id_ed25519.pub') }}"
        manage_dir: false
      register: auth_key

    - name: Set proper permissions to user's SSH config dir
      file:
        path: "{{ auth_key.keyfile | dirname }}"
        state: directory
        owner: "{{ auth_key.user }}"
        mode: "0700"

    - name: Set proper permissions to the authorized key
      file:
        path: "{{ auth_key.keyfile }}"
        state: file
        owner: "{{ auth_key.user }}"
        mode: "0600"

- name: Include sudo files
  lineinfile:
    dest: /etc/sudoers
    line: '#includedir /etc/sudoers.d'
    validate: 'visudo -cf %s'

- name: Add user to sudoers
  lineinfile:
    dest: '/etc/sudoers.d/{{ user_name }}'
    line: '{{ user_name }} ALL=(ALL) ALL'
    create: true
    validate: 'visudo -cf %s'
    mode: "0644"
