---
# Defines a user.
#
# TODO: Place *.rc files under /etc/skel.

# Later you need to set password, i.e., $ sudo passwd {{ user_name }}
- name: Create a user with a disabled password
  user:
    name: '{{ user_name }}'
    comment: '{{ user_gecos }}'
    password: '!'
    shell: /bin/bash
    generate_ssh_key: yes
  register: user_result

- name: Provide an authorized key
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', '{{ user_result.home }}/.ssh/id_rsa.pub') }}"
    manage_dir: no

- name: Include sudo files
  lineinfile:
    dest: /etc/sudoers
    line: '#includedir /etc/sudoers.d'
    validate: 'visudo -cf %s'

- name: Add user to sudoers
  lineinfile:
    dest: '/etc/sudoers.d/{{ user_name }}'
    line: '{{ user_name }} ALL=(ALL) ALL'
    create: yes
    validate: 'visudo -cf %s'
