---
# Install Gradle.

- name: Ensure gradle directory exists
  file:
    path: /opt/gradle
    state: directory

- name: Download gradle distribution and extract excutable
  unarchive:
    src: https://services.gradle.org/distributions/gradle-6.5-bin.zip
    dest: /opt/gradle
    remote_src: yes
