---
# Install Node.js. An official deb package is available.

# Node.js
- name: Ensure a dependency of Node.js is present
  apt:
    name: gyp

- name: Add an apt key from a NodeSource's key server
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

# Node.js repo
- name: Add node.js repo
  apt_repository:
    filename: nodesource
    repo: deb https://deb.nodesource.com/{{ nodejs_version }} {{ nodejs_release }} main

# Node.js source repo
- name: Add node.js src repo
  apt_repository:
    filename: nodesource
    repo: deb-src https://deb.nodesource.com/{{ nodejs_version }} {{ nodejs_release }} main

- name: Ensure Node.js is up to date
  apt:
    update_cache: yes
    name: nodejs

# Segmentation fault on aarch64 Docker # Yarn
# - name: Add an apt key from a yarnpkg's key server
#   apt_key:
#     url: https://dl.yarnpkg.com/debian/pubkey.gpg
#
# - name: Add Yarn repo
#   apt_repository:
#     filename: yarn
#     repo: deb https://dl.yarnpkg.com/debian/ stable main
#
# - name: Ensure Yarn is up to date
#   apt:
#     update_cache: yes
#     name: yarn
