---
# Install Node.js. An official deb package is available.

# Node.js
- name: Ensure a dependency of Node.js is present
  apt:
    name: gyp

- name: Add an apt key from a NodeSource's key server
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

# Node.js repo
- name: Add node.js repo
  apt_repository:
    filename: nodesource
    repo: deb https://deb.nodesource.com/{{ nodejs_version }} {{ nodejs_release }} main

# Node.js source repo
- name: Add node.js src repo
  apt_repository:
    filename: nodesource
    repo: deb-src https://deb.nodesource.com/{{ nodejs_version }} {{ nodejs_release }} main

- name: Ensure Node.js is up to date
  apt:
    update_cache: true
    name: nodejs

# Setting up Chrome Linux sandbox for puppeteer
- name: Enable user namespace cloning
  ansible.posix.sysctl:
    name: kernel.unprivileged_userns_clone
    value: '1'
    state: present
