---
# Prepare installation directory
- name: Ensure default installation directory exists
  file:
    path: "{{ ansible_env.HOME }}/opt"
    state: directory

# Install Flutter UI framework.
- name: Install Flutter
  unarchive:
    src: https://storage.googleapis.com/flutter_infra/releases/dev/linux/flutter_linux_1.24.0-7.0.pre-dev.tar.xz
    dest: "{{ ansible_env.HOME }}/opt"
    remote_src: yes

- name: Add path to user's local path env
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.profile"
    line: 'export PATH=$PATH:$HOME/opt/flutter/bin'

# Configure Flutter for web development
- name: Enable web support
  command: "{{ ansible_env.HOME|quote }}/opt/flutter/bin/flutter config --enable-web"

# Configure Flutter for linux desktop development
- name: Enable linux desktop support
  command: "{{ ansible_env.HOME|quote }}/opt/flutter/bin/flutter config --enable-linux-desktop"
