---

- name: Install JVM friends
  import_role:
    name: comcast.sdkman
  vars:
    sdkman_auto_answer: true
    sdkman_install_packages:
      - { candidate: java, version: 17.0.3-tem }
      - { candidate: gradle, version: 7.4.2 }
      - { candidate: maven, version: 3.8.5 }
      - { candidate: sbt, version: 1.6.2 }

- name: Install OpenAPI Generator
  block:
    - name: Create OpenAPI tools installation directory
      file:
        path: "{{ ansible_env.HOME }}/bin/openapitools"
        state: directory
        mode: "0755"

    - name: Download Bash Launcher Script
      get_url:
        url: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh
        dest: "{{ ansible_env.HOME }}/bin/openapitools/openapi-generator-cli"
        mode: "0751"

    - name: Add path to user's local path env
      lineinfile:
        dest: "{{ ansible_env.HOME }}/.profile"
        line: 'export PATH=$PATH:$HOME/bin/openapitools'
