---
# Install SBT from an official deb repository.

# SBT repo
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823

- name: Add SBT repo
  apt_repository:
    filename: sbt
    repo: deb https://dl.bintray.com/sbt/debian /

- name: Ensure sbt is up to date
  apt:
    update_cache: yes
    name: sbt
    state: latest
