---
# Enhance CLI life

- name: Install tmux
  apt:
    name: tmux
    state: present

- name: Place tmux config file
  template:
    src: .tmux.conf
    dest: /etc/skel/.tmux.conf
    mode: u+rw

- name: Install spell checker
  apt:
    name: hunspell
    state: present

- name: Place nano config file
  template:
    src: .nanorc
    dest: /etc/skel/.nanorc
    mode: u+rw

- name: Install w3m text-based web browser
  apt:
    name: w3m
    state: present

- name: Install misc utils
  apt:
    name: tree, jq
    state: present
