---
#

- name: Move Ctrl key
  lineinfile:
    dest: /etc/default/keyboard
    regexp: '^XKBOPTIONS='
    line: XKBOPTIONS="ctrl:nocaps"

- name: Reflect changes to the config file
  shell: dpkg-reconfigure -phigh console-setup
