---
# Environment settings after installation
- name: Add path to user's path env (bare-metal)
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.profile"
    line: 'export PATH=$PATH:/usr/local/gcc-arm-none-eabi-9-2020-q2-update/bin'

- name: Add path to user's path env (linux-based)
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.profile"
    line: 'export PATH=$PATH:/usr/local/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf/bin'
