---
# Python 3 environment

- name: Create Python 3 venv dir
  file:
    path: "{{ ansible_env.HOME }}/python_projects"
    state: directory

- name: Install virtualenv via pip3
  pip:
    name: virtualenv
    executable: pip3

- name: Install Ansible Lint
  pip:
    name: ansible-lint
    virtualenv: "{{ ansible_env.HOME }}/python_projects"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

- name: Install Sphinx
  pip:
    name: sphinx
    virtualenv: "{{ ansible_env.HOME }}/python_projects"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

- name: Install Meson
  pip:
    name: meson, ninja, cmake
    virtualenv: "{{ ansible_env.HOME }}/python_projects"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
