---
# Python 3 environment

- name: Create Python 3 venv dir
  file:
    path: "{{ ansible_env.HOME }}/python_projects"
    state: directory
    mode: 0755

- name: Install virtualenv via pip3
  pip:
    name: virtualenv
    executable: pip3

- name: Install Ansible Lint
  pip:
    name: ansible, ansible-lint
    virtualenv: "{{ ansible_env.HOME }}/python_projects"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

- name: Install Sphinx
  pip:
    name: sphinx, restview, rst2beamer3k
    virtualenv: "{{ ansible_env.HOME }}/python_projects"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

- name: Install Meson Build
  pip:
    name: meson
    virtualenv: "{{ ansible_env.HOME }}/python_projects"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

- name: Install IPython
  pip:
    name: ipython
    virtualenv: "{{ ansible_env.HOME }}/python_projects"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

- name: Install Black
  pip:
    name: black
    virtualenv: "{{ ansible_env.HOME }}/python_projects"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
