---
# Install Terraform from an official deb repository.

# Terraform repo
- name: Add Hashicorp Stable APT repository
  deb822_repository:
    name: hashicorp
    types: deb
    uris: "https://apt.releases.hashicorp.com"
    signed_by: "https://apt.releases.hashicorp.com/gpg"
    suites: "{{ ansible_distribution_release|lower }}"
    components: main

- name: Update and install Terraform
  apt:
    update_cache: true
    name: terraform
