---
# Install Terraform from an official deb repository.

# Terraform repo
- name: Add the HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: Add the official HashiCorp Linux repository
  apt_repository:
    filename: terraform
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }}  main

- name: Update and install Terraform
  apt:
    update_cache: yes
    name: terraform
