---
# Install AdoptOpenJDK from an official deb repository.

# AdoptOpenJDK repo
- name: Add an apt key by id from a keyserver
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

- name: Add AdoptOpenJDK repo
  apt_repository:
    filename: adoptopenjdk
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb {{ ansible_distribution_release }} main

- name: Ensure AdoptOpenJDK is up to date
  apt:
    update_cache: yes
    name: adoptopenjdk-11-hotspot
    state: latest
