---
#
# Docker repo
- name: Add Docker's official GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ docker_distro }}/gpg"

- name: Add Docker repo
  apt_repository:
    filename: sbt
    repo: "deb [arch=amd64]
      https://download.docker.com/linux/{{ docker_distro }}
      {{ docker_release }}
      stable"

- name: Ensure Docker is up to date
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Fetch docker-compose executable
  uri:
    url: "https://github.com/docker/compose/releases/download/\
      1.26.2/\
      docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: u+x
